Repository sylikc/jpegview, pull requests merged in 2023-10, with the labels that each got.

#242 Show acquisition date from RAW metadata in window title
  src/JPEGView/MainDlg.cpp
Labels: enhancement, format support

#233 Basic PSD decoding support
  README.md
  src/JPEGView.Setup/Product.wxs
  src/JPEGView/EXIFDisplayCtl.cpp
  src/JPEGView/EXIFReader.cpp
  src/JPEGView/EXIFReader.h
  src/JPEGView/FileExtensionsDlg.cpp
  src/JPEGView/FileList.cpp
  src/JPEGView/Helpers.cpp
  src/JPEGView/Helpers.h
  src/JPEGView/ICCProfileTransform.cpp
  src/JPEGView/ICCProfileTransform.h
  src/JPEGView/ImageLoadThread.cpp
  src/JPEGView/ImageLoadThread.h
  src/JPEGView/ImageProcessingTypes.h
  src/JPEGView/JPEGView.vcxproj
  src/JPEGView/JPEGView.vcxproj.filters
  src/JPEGView/MaxImageDef.h
  src/JPEGView/PSDWrapper.cpp
  src/JPEGView/PSDWrapper.h
  src/JPEGView/ReaderTGA.cpp
Labels: format support

#250 Update strings_ja.txt
  src/JPEGView/Config/strings_ja.txt
Labels: localization
