Repository sylikc/jpegview, pull requests merged in 2023-02, with the labels that each got.

#137 Update strings_zh.txt
  src/JPEGView/Config/strings_zh.txt
Labels: localization

#138 Update strings_zh.txt
  src/JPEGView/Config/strings_zh.txt
Labels: localization

#145 Fix transparency color being applied incorrectly
  src/JPEGView/ImageLoadThread.cpp
  src/JPEGView/ReaderTGA.cpp
Labels: bug

#149 Use GDI+ to load PNGs when ForceGDIPlus or UseEmbeddedColorProfiles is true
  src/JPEGView/ImageLoadThread.cpp
Labels: enhancement
