Repository sylikc/jpegview, pull requests merged in 2024-06, with the labels that each got.

#308 psd: properly skip image resource names
  src/JPEGView/PSDWrapper.cpp
Labels: format support

#310 Fix CR3 detection
  src/JPEGView/Helpers.cpp
  src/JPEGView/ImageLoadThread.cpp
Labels: format support

#305 Implement AVIF transformations
  src/JPEGView/AVIFWrapper.cpp
  src/JPEGView/BasicProcessing.cpp
  src/JPEGView/BasicProcessing.h
  src/JPEGView/JPEGImage.cpp
Labels: enhancement, format support

#265 Support EXIF data in PNGs when using GDI+
  src/JPEGView/ImageLoadThread.cpp
  src/JPEGView/PNGWrapper.cpp
  src/JPEGView/PNGWrapper.h
Labels: format support

#311 Fix decoding K25 raw images
  src/JPEGView/ImageLoadThread.cpp
  src/JPEGView/RAWWrapper.cpp
Labels: format support

#312 psd: use byte counts for scan lines
  src/JPEGView/PSDWrapper.cpp
Labels: format support

#298 Config: OverrideOriginalFileWithoutSaveDialog -> OverwriteOriginalFileWithoutSaveDialog
  src/JPEGView/Config/JPEGView.ini.tpl
  src/JPEGView/Config/JPEGView_ru.ini
  src/JPEGView/Config/JPEGView_ru.ini.tpl
  src/JPEGView/Config/readme.html
  src/JPEGView/Config/readme_ru.html
  src/JPEGView/Config/readme_uk.html
Labels: bug, config opts
